project_id = "astugmzoxhxcyipxsojl"

[functions.tmdb-search]
verify_jwt = false

[functions.tmdb-details]
verify_jwt = false

[functions.tmdb-seasons]
verify_jwt = false

[functions.stripe-payment]
verify_jwt = false

[functions.flutterwave-payment]
verify_jwt = false

[functions.send-subscription-email]
verify_jwt = false

[functions.check-expiring-subscriptions]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.generate-upload-url]
verify_jwt = false

[functions.transcode-video]
verify_jwt = false

[functions.mux-video]
verify_jwt = false
